# Numpy

In [3]:
pip install numpy as np

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement as (from versions: none)
ERROR: No matching distribution found for as


In [4]:
import numpy as np

# creating 1D array

In [6]:
g=[12,4,52,74]
b=np.array(g)

# 3D array

In [11]:
g=[[[23,34,23]],[[12,432,1]],[[23,52,64]]]
b=np.array(g)
print(b)
print(type(b))
print(b.ndim)

[[[ 23  34  23]]

 [[ 12 432   1]]

 [[ 23  52  64]]]
<class 'numpy.ndarray'>
3


# Pandas Installation

In [12]:
pip install pandas

   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ------- -------------------------------- 2.1/11.0 MB 17.1 MB/s eta 0:00:01
   ----------------------- ---------------- 6.6/11.0 MB 19.7 MB/s eta 0:00:01
   -------------------------- ------------- 7.3/11.0 MB 14.2 MB/s eta 0:00:01
   -------------------------------- ------- 8.9/11.0 MB 11.8 MB/s eta 0:00:01
   ---------------------------------------  10.7/11.0 MB 11.3 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 10.3 MB/s  0:00:01

   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   -------------

In [1]:
import pandas as pd


In [7]:
g=[12,4,52,74]
df=pd.Series(g)

df1=pd.DataFrame(g)

In [10]:
data={'Name':['A','B'],
      'place':['ABC','DEF']}
df3=pd.DataFrame(data)

In [ ]:
print(df,df1)

0    12
1     4
2    52
3    74
dtype: int64     0
0  12
1   4
2  52
3  74


In [11]:
print(df3)

  Name place
0    A   ABC
1    B   DEF
